name: Django Main Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run Unit Tests
        run: |
          python manage.py test --verbosity=2 --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner --output-file=test-results.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-results.xml

      - name: Collect static files (Django-specific)
        env:
          DJANGO_SETTINGS_MODULE: IPS_41_Lab1_django.settings
        run: |
          python manage.py collectstatic --noinput

      - name: Create build artifact
        run: |
          zip -r project_artifact.zip . -x "*.git*" "*.github*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: django-project-artifact
          path: project_artifact.zip
